import {
  faArrowRightToCity,
  faBanSmoking,
  faDoorOpen,
  faElevator,
  faFan,
  faFireBurner,
  faHotTubPerson,
  faIcicles,
  faJugDetergent,
  faKitchenSet,
  faMattressPillow,
  faMugHot,
  faPlug,
  faShirt,
  faSoap,
  faSprayCanSparkles,
  faTemperatureLow,
  faTv,
  faUtensils,
  faWifi,
  faSquare,
  faHandsBubbles,
  faTable,
  faHandshakeAngle,
  faCouch,
  faCarOn,
  faSquareParking,
  faPersonChalkboard,
  faHouseLaptop,
  faCity,
} from "@fortawesome/free-solid-svg-icons";
export const amenitiesOptions = [
  { value: "Breakfast", label: "Breakfast", icon: faUtensils },
  { value: "Lunch", label: "Lunch", icon: faUtensils },
  { value: "Dinner", label: "Dinner", icon: faUtensils },
  { value: "Kitchen", label: "Kitchen", icon: faKitchenSet },
  { value: "City View", label: "City View", icon: faArrowRightToCity },
  { value: "Workspace", label: "Workspace", icon: faHouseLaptop },
  { value: "Wifi", label: "Wifi", icon: faWifi },
  { value: "Lift", label: "Lift", icon: faElevator },
  {
    value: "Private Balcony",
    label: "Private Balcony",
    icon: faDoorOpen,
  },
  {
    value: "Washing Machine",
    label: "Washing Machine",
    icon: faJugDetergent,
  },
  { value: "Hair Dryer", label: "Hair Dryer", icon: faPlug },
  {
    value: "Soaps",
    label: "Soaps",
    icon: faSoap,
  },
  { value: "Shower Gel", label: "Shower Gel", icon: faSprayCanSparkles },
  {
    value: "Bathroom Heater",
    label: "Bathroom Heater",
    icon: faHotTubPerson,
  },
  {
    value: "Pillows and Blankets",
    label: "Pillows and Blankets",
    icon: faMattressPillow,
  },
  { value: "Iron", label: "Iron", icon: faShirt },
  {
    value: "Air Conditioning",
    label: "Air Conditioning",
    icon: faTemperatureLow,
  },
  {
    value: "Fan",
    label: "Fan",
    icon: faFan,
  },
  { value: "HDTV", label: "HDTV", icon: faTv },
  { value: "Smoke Alaram", label: "Smoke Alaram", icon: faBanSmoking },
  { value: "Refrigirator", label: "Refrigirator", icon: faIcicles },
  {
    value: "Cooking Applicances",
    label: "Cooking Applicances",
    icon: faFireBurner,
  },
  { value: "Microwave", label: "Microwave", icon: faSquare },
  { value: "Dishwasher", label: "Dishwasher", icon: faHandsBubbles },
  { value: "Kettle", label: "Kettle", icon: faMugHot },
  { value: "Dining Table", label: "Dining Table", icon: faTable },
  {
    value: "Host Assistance",
    label: "Host Assistance",
    icon: faHandshakeAngle,
  },
  { value: "Sofa", label: "Sofa", icon: faCouch },
  {
    value: "Tour Assistance",
    label: "Tour Assistance",
    icon: faCarOn,
  },
  { value: "Parking", label: "Parking", icon: faSquareParking },
  { value: "Room Service", label: "Room Service", icon: faPersonChalkboard },
];
