export const theme = {
  colors: {
    primaryColor: "#015151",
    whiteColor: "#ffffff",
    blackColor: "#333333",
    lightgreenColor: "#079d9d",
    greyColor: "#00000059",
    ratingColor: "#ffd700",
    labelColor: "#00000059",
    primaryBtnColor: "#015151",
  },
  bigScreens: {
    navButtonFont: "22px",
    titleFont: "32px",
    labelFont: "18px",
    inputFont: "27px",
    fontsize: "30px",
    subFontSize: "28px",
    searchinputfontsize: "20px",
    optionfontsize: "22px",
    btnFontsize: "26px",
    cardlocation: "14px",
    cardhousetitle: "12px",
    carddesc: "10px",
    cardrating: "12px",

    /**
    navButtonFont: "22px",
    titleFont: "32px",
    labelFont: "18px",
    inputFont: "27px",
    fontsize: "30px",
    subFontsize: "28px",
    searchinputfontsize: "20px",
    optionfontsize: "22px",
    btnFontsize: "26px",
    cardprice: "20px",
    cardlocation: "14px",
    cardhousetitle: "12px",
    carddesc: "10px",
    cardrating: "12px",

     */
  },
  tabletAndIpadScreens: {
    navButtonFont: "14px",
    titleFont: "30px",
    labelFont: "14px",
    inputFont: "16px",
    fontsize: "24px",
    subFontSize: "28px",
    searchinputfontsize: "12px",
    optionfontsize: "22px",
    btnFontsize: "16px",
    cardprice: "20px",
    cardlocation: "16px",
    cardhousetitle: "18px",
    carddesc: "12px",
    cardrating: "16px",

    /**
    navButtonFont: "14px",
    titleFont: "30px",
    labelFont: "14px",
    inputFont: "22px",
    fontsize: "24px",
    subFontSize: "28px",
    searchinputfontsize: "12px",
    optionfontsize: "22px",
    btnFontsize: "26px",
    cardprice: "20px",
    cardlocation: "16px",
    cardhousetitle: "18px",
    carddesc: "12px",
    cardrating: "16px",

     */
  },
  smallTabScreens: {
    navButtonFont: "12px",
    titleFont: "26px",
    labelFont: "10px",
    inputFont: "12px",
    fontsize: "20px",
    subFontSize: "18px",
    searchinputfontsize: "12px",
    optionfontsize: "15px",
    btnFontsize: "16px",
    cardprice: "18px",
    cardlocation: "14px",
    cardhousetitle: "16px",
    carddesc: "10px",
    cardrating: "12px",

    /**
    navButtonFont: "12px",
    titleFont: "26px",
    labelFont: "10px",
    inputFont: "14px",
    fontsize: "20px",
    subFontSize: "18px",
    searchinputfontsize: "12px",
    optionfontsize: "15px",
    btnFontsize: "16px",
     */
  },
  mobileScreens: {
    navButtonFont: "12px",
    titleFont: "26px",
    labelFont: "8px",
    inputFont: "10px",
    fontsize: "12px",
    subFontSize: "10px",
    searchinputfontsize: "12px",
    optionfontsize: "15px",
    btnFontsize: "10px",
    cardprice: "18px",
    cardlocation: "14px",
    cardhousetitle: "16px",
    carddesc: "10px",
    cardrating: "12px",

    /**
    navButtonFont: "12px",
    titleFont: "26px",
    labelFont: "8px",
    inputFont: "10px",
    fontsize: "12px",
    subFontSize: "10px",
    searchinputfontsize: "12px",
    optionfontsize: "15px",
    btnFontsize: "10px",
     */
  },

  cards: {
    cardMaintitle: "28px",
    cardSubtitle: "26px",
  },
};
